# Generated by Django 5.0.1 on 2024-01-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_menu_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='category',
            field=models.CharField(blank=True, choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Pasta', 'Pasta'), ('Fries', 'Fries')], max_length=10, null=True),
        ),
    ]
