# Generated by Django 5.0.1 on 2024-01-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='menu_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resturant.category'),
        ),
    ]
