# Generated by Django 5.0.1 on 2024-01-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0005_menu_items_menu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_items',
            name='category',
        ),
    ]
